### ISSUE TITLE
Code merging method

### ISSUE THREAD

**Issue by binhwpo** [xydac/WP-Ultimate-CMS#2]
Hi Deepak,

Let's continue our development over here so that your blog is cleaner.

For pull requests or branching, It's up to your decision. But I would like to share my experience here.

In the past we got a small project with 3 developers. We end up having over 1000 pull requests, each have a few commits. Total out thousands of commits.

The project became a bunch of mess with hard to reverse actions. The main reasons became that in order to test something, we had to pull to the test branch, then from the test result, we pull again to the master. Which ended up 2 pulls for 1 change.

That's why I propose at first we should start up clean with branching. You make a dev branch, I push commits into it. Then we can test it together, when it's really ready for production, you merge to master. 

The issues are used to track new features and bugs. Not to manage merging.

That way, we only have commits to manage. Cleaner, faster.

But anyway, method is not as important as the product. You are the head. I will fork it and leave that decision to you for the time being.

Cheers,
Binh

**Comment by xydac** [comment]
Sure Binh, Its not a problem. Its just that I wanted to start as pull request and further we can do as you suggested. Just give me sometime

Thanks for your support.

-Deepak
