### ISSUE TITLE
Changing home tabs

### ISSUE THREAD

**Issue by binhwpo** [xydac/WP-Ultimate-CMS#3]
Hi @xydac ,

I told you earlier on that the Home tab is currently confusing. As after installation people will bump their head here and don't know what to do next. Hence I'd strongly suggest to move the Module Manager to firs position, because that's what people need to do first: enabling modules.

I'm tried to modify the tabs. Doing the following:

1. Rename "Home" to "Data Sync" (easy)

2. Switch position of tabs to: Module Manager | Data Sync (very hard)

I'm still new to the code and it's just a little over-complicated. Could you please either do this by yourself or explain to me how to change order of the tabs?

Thanks.

**Comment by xydac** [comment]
This is not a very big change.
I can do this.

-Deepak

**Comment by xydac** [comment]
@binhwpo  Fixed this in Develop Branch :+1:

**Comment by binhwpo** [comment]
@xydac That's very cool mate. Thanks for reacting so quickly. 

Just 1 more request, if we could get the develop branch to "dev" for faster git command typing, really appreciated.

**Comment by binhwpo** [comment]
BTW: Tested and it worked.
